// Command dbbootstrap creates the four database roles on a managed Postgres
// that has no init script.
//
//	go run ./scripts/dbbootstrap -out C:\path\outside\the\repo\db.env
//
// It exists because the role separation this system depends on (PART 101) is
// created three different ways depending on where Postgres came from. Locally,
// docker/postgres/init/001_roles.sql runs at container creation. On AWS, a
// one-shot task does it with secrets from Secrets Manager. On a managed free
// tier there is no init hook and no bootstrap task, so it is this.
//
// The roles are not a convenience. cp_app is deliberately given no default
// table privileges at all: every migration grants exactly what the application
// needs on the table it creates, so a table with no explicit grant is
// unreadable by the application rather than readable by accident. Running the
// migrations as the owner role and letting the application connect as that same
// owner would quietly delete that property, which is why this refuses to be
// skipped.
//
// Passwords are generated here, never chosen, and are written only to the file
// named by -out. Nothing sensitive reaches stdout, a log or a shell history:
// this program has no flag that prints a password.
package main

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"flag"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/jackc/pgx/v5"
)

// roles are created in this order. cp_migrate owns the schema; the other three
// only ever receive what a migration grants them.
var roles = []struct {
	name string
	// why is printed next to the role, so an operator reading the output knows
	// what they have just created and what would break without it.
	why string
}{
	{"cp_migrate", "owns the schema and runs migrations; the only role that may create or alter tables"},
	{"cp_app", "the application. No default table privileges: each migration grants exactly what it needs"},
	{"cp_readonly", "analytics reads. SELECT everywhere, writes nowhere"},
	{"cp_ops", "operations and retention passes. Reads, plus the deletes retention needs"},
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "dbbootstrap:", err)
		os.Exit(1)
	}
}

func run() error {
	out := flag.String("out", "", "file to write the generated role URLs to; must be outside the repository")
	adminEnv := flag.String("admin-env", "CP_BOOTSTRAP_ADMIN_URL", "environment variable holding the owner connection string")
	timeout := flag.Duration("timeout", 60*time.Second, "overall timeout")
	flag.Parse()

	if strings.TrimSpace(*out) == "" {
		return errors.New("-out is required; role passwords are written to a file rather than to a terminal")
	}
	abs, err := filepath.Abs(*out)
	if err != nil {
		return err
	}
	// A generated credential inside a working tree is one `git add -A` away
	// from being permanent and public. Refusing the path is cheaper than
	// trusting .gitignore.
	if inRepo, err := underRepo(abs); err != nil {
		return err
	} else if inRepo {
		return fmt.Errorf("-out %s is inside the repository; write role passwords outside it", abs)
	}

	admin := strings.TrimSpace(os.Getenv(*adminEnv))
	if admin == "" {
		return fmt.Errorf("%s is not set; it must hold the connection string of a role that may CREATE ROLE", *adminEnv)
	}

	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()

	conn, err := pgx.Connect(ctx, admin)
	if err != nil {
		// The URL is not quoted: it carries a password.
		return errors.New("could not connect with the admin connection string")
	}
	defer func() { _ = conn.Close(ctx) }()

	var dbName string
	if err := conn.QueryRow(ctx, `SELECT current_database()`).Scan(&dbName); err != nil {
		return fmt.Errorf("reading the current database: %w", err)
	}
	fmt.Printf("connected to %q\n", dbName)

	lines := []string{
		"# GENERATED by scripts/dbbootstrap. Role passwords for " + dbName + ".",
		"# Never commit this file. Never paste its contents anywhere.",
	}

	for _, r := range roles {
		pw, err := password()
		if err != nil {
			return err
		}
		// Idempotent: an existing role has its password reset rather than
		// being skipped, because a bootstrap that leaves a role with a
		// password nobody has is a bootstrap that has to be undone by hand.
		// The identifiers are constants from the table above, never input.
		stmt := fmt.Sprintf(`DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '%s') THEN
    ALTER ROLE %s WITH LOGIN PASSWORD %s;
  ELSE
    CREATE ROLE %s LOGIN PASSWORD %s;
  END IF;
END $$;`, r.name, r.name, quote(pw), r.name, quote(pw))
		if _, err := conn.Exec(ctx, stmt); err != nil {
			return fmt.Errorf("creating %s: %w", r.name, err)
		}
		fmt.Printf("  %-12s %s\n", r.name, r.why)

		u, err := roleURL(admin, r.name, pw)
		if err != nil {
			return err
		}
		lines = append(lines, strings.ToUpper(r.name)+"_URL="+u)
	}

	// Connect and schema privileges. cp_app deliberately gets no default table
	// privileges; see the package comment.
	grants := []string{
		fmt.Sprintf(`GRANT ALL PRIVILEGES ON DATABASE %s TO cp_migrate`, quoteIdent(dbName)),
		fmt.Sprintf(`GRANT CONNECT ON DATABASE %s TO cp_app, cp_readonly, cp_ops`, quoteIdent(dbName)),
		`GRANT USAGE ON SCHEMA public TO cp_app, cp_readonly, cp_ops`,
		`GRANT CREATE, USAGE ON SCHEMA public TO cp_migrate`,
	}
	for _, g := range grants {
		if _, err := conn.Exec(ctx, g); err != nil {
			return fmt.Errorf("grant %q: %w", g, err)
		}
	}

	// Membership before default privileges, and the order is not cosmetic.
	// Managed Postgres does not hand out superuser, and
	// ALTER DEFAULT PRIVILEGES FOR ROLE cp_migrate is refused unless the caller
	// is a member of cp_migrate. Attempted the other way round it fails with a
	// permission error that reads like a missing privilege on the schema.
	var adminRole string
	if err := conn.QueryRow(ctx, `SELECT current_user`).Scan(&adminRole); err != nil {
		return fmt.Errorf("reading the current user: %w", err)
	}
	if _, err := conn.Exec(ctx, fmt.Sprintf(`GRANT cp_migrate TO %s`, quoteIdent(adminRole))); err != nil {
		return fmt.Errorf("granting cp_migrate to %s, which is what allows its default privileges to be set: %w", adminRole, err)
	}

	// The read roles get a default SELECT; cp_app deliberately gets none. See
	// the package comment: a table with no explicit grant must be unreadable by
	// the application rather than readable by accident.
	defaults := []string{
		`ALTER DEFAULT PRIVILEGES FOR ROLE cp_migrate IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO cp_app`,
		`ALTER DEFAULT PRIVILEGES FOR ROLE cp_migrate IN SCHEMA public GRANT SELECT ON TABLES TO cp_readonly, cp_ops`,
	}
	for _, d := range defaults {
		if _, err := conn.Exec(ctx, d); err != nil {
			return fmt.Errorf("default privileges %q: %w", d, err)
		}
	}

	if _, err := conn.Exec(ctx, `ALTER SCHEMA public OWNER TO cp_migrate`); err != nil {
		return fmt.Errorf("giving cp_migrate ownership of schema public: %w", err)
	}

	// #nosec G703 -- the destination is the operator's own -out flag, and being
	// caller-chosen is the entire point: role passwords must land outside the
	// repository, which underRepo above enforces. This program reads no
	// untrusted input.
	if err := os.WriteFile(abs, []byte(strings.Join(lines, "\n")+"\n"), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", abs, err)
	}
	fmt.Printf("wrote %d role URLs to %s\n", len(roles), abs)
	fmt.Println("nothing sensitive was printed; the passwords exist only in that file")
	return nil
}

// underRepo reports whether p is inside a git working tree.
func underRepo(p string) (bool, error) {
	dir := filepath.Dir(p)
	for {
		if _, err := os.Stat(filepath.Join(dir, ".git")); err == nil {
			return true, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return false, nil
		}
		dir = parent
	}
}

// password returns 32 bytes of randomness, base64url encoded so it survives a
// connection string without escaping.
func password() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generating a password: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// quote renders a SQL string literal.
func quote(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

// quoteIdent renders a SQL identifier.
func quoteIdent(s string) string { return `"` + strings.ReplaceAll(s, `"`, `""`) + `"` }

// roleURL rewrites the admin connection string's credentials, keeping every
// other part of it -- host, database, sslmode, and any provider-specific
// parameter the string carries.
func roleURL(admin, role, pw string) (string, error) {
	u, err := url.Parse(admin)
	if err != nil {
		return "", errors.New("the admin connection string is not a URL")
	}
	u.User = url.UserPassword(role, pw)
	return u.String(), nil
}
