/**
 * The operator-authority model, loaded from `src/generated/authority.json`.
 *
 * That file is generated by `internal/adminplane` from `internal/security`,
 * `internal/admin`, `internal/gates` and `internal/killswitch`, and a Go golden
 * test fails if it goes stale. Nothing in this console may hard-code a
 * permission, a step-up window, an expiry or a kill-switch severity: read it
 * from here, or the console will eventually promise an authority the server
 * does not grant.
 *
 * Regenerate with:
 *   go test ./internal/adminplane -run TestAuthorityGolden -update-authority
 */

export type Permission = string;
export type Role = string;
export type ActionKindName = string;

export interface RoleGrant {
  readonly role: Role;
  readonly permissions: readonly Permission[];
  /** false only for BREAK_GLASS, whose grants expire on a clock. */
  readonly standing: boolean;
}

export interface ActionKind {
  readonly kind: ActionKindName;
  readonly requires_dual: boolean;
  readonly propose_permission: Permission;
  readonly approve_permission?: Permission;
  readonly step_up_max_age_seconds: number;
  readonly expiry_seconds: number;
  /** true when only a live break-glass elevation can supply the approval. */
  readonly requires_break_glass_approval: boolean;
}

export interface GateAction {
  readonly action: string;
  readonly permission: Permission;
  readonly step_up_max_age_seconds: number;
}

export interface KillSwitchKind {
  readonly kind: string;
  readonly severity: "STANDARD" | "SEVERE";
  readonly release_needs_approval: boolean;
}

export interface SurfaceWrite {
  readonly id: string;
  readonly any_of: readonly Permission[];
  readonly step_up_max_age_seconds?: number;
  readonly requires_reason: boolean;
  readonly requires_evidence?: boolean;
  readonly approval_kind?: ActionKindName;
  readonly approval_condition?: string;
  readonly never_for_agent: boolean;
}

export interface Surface {
  readonly id: string;
  readonly read_any_of: readonly Permission[];
  readonly writes?: readonly SurfaceWrite[];
  readonly action_kinds?: readonly ActionKindName[];
}

export interface BreakGlassPolicy {
  readonly role: Role;
  readonly kind: ActionKindName;
  readonly max_duration_seconds: number;
  readonly grants: readonly Permission[];
}

export interface Authority {
  readonly version: number;
  readonly source: string;
  readonly min_reason_length: number;
  readonly permissions: readonly Permission[];
  readonly dual_control_permissions: readonly Permission[];
  readonly agent_permissions: readonly Permission[];
  readonly roles: readonly RoleGrant[];
  readonly action_kinds: readonly ActionKind[];
  readonly action_statuses: readonly string[];
  readonly action_transitions: Readonly<Record<string, readonly string[]>>;
  readonly verbs: readonly string[];
  readonly reasons: readonly string[];
  readonly gate_actions: readonly GateAction[];
  readonly capabilities: readonly string[];
  readonly kill_switch_kinds: readonly KillSwitchKind[];
  readonly surfaces: readonly Surface[];
  readonly break_glass: BreakGlassPolicy;
}

/** The schema version this console was written against. */
export const SUPPORTED_AUTHORITY_VERSION = 1;

function fail(what: string): never {
  throw new Error(`authority document is not usable: ${what}`);
}

/**
 * Validates the shape of a parsed authority document. It is deliberately
 * strict: a console that renders half a permission matrix is worse than one
 * that refuses to start, because the half it renders looks authoritative.
 */
export function parseAuthority(value: unknown): Authority {
  if (typeof value !== "object" || value === null) fail("not an object");
  const doc = value as Record<string, unknown>;
  if (doc["version"] !== SUPPORTED_AUTHORITY_VERSION) {
    fail(`version ${String(doc["version"])} is not the ${SUPPORTED_AUTHORITY_VERSION} this console understands`);
  }
  for (const key of [
    "permissions",
    "dual_control_permissions",
    "agent_permissions",
    "roles",
    "action_kinds",
    "action_statuses",
    "verbs",
    "reasons",
    "gate_actions",
    "capabilities",
    "kill_switch_kinds",
    "surfaces",
  ]) {
    if (!Array.isArray(doc[key]) || (doc[key] as unknown[]).length === 0) fail(`${key} is missing or empty`);
  }
  if (typeof doc["min_reason_length"] !== "number" || doc["min_reason_length"] < 1) {
    fail("min_reason_length is missing");
  }
  if (typeof doc["break_glass"] !== "object" || doc["break_glass"] === null) fail("break_glass is missing");
  if (typeof doc["action_transitions"] !== "object" || doc["action_transitions"] === null) {
    fail("action_transitions is missing");
  }
  return doc as unknown as Authority;
}

/** Index of role name to permission set, built once. */
export class AuthorityIndex {
  readonly doc: Authority;
  private readonly rolePermissions: Map<Role, ReadonlySet<Permission>>;
  private readonly kinds: Map<ActionKindName, ActionKind>;
  private readonly agentPermissions: ReadonlySet<Permission>;
  private readonly dualControl: ReadonlySet<Permission>;

  constructor(doc: Authority) {
    this.doc = doc;
    this.rolePermissions = new Map(doc.roles.map((r) => [r.role, new Set(r.permissions)] as const));
    this.kinds = new Map(doc.action_kinds.map((k) => [k.kind, k] as const));
    this.agentPermissions = new Set(doc.agent_permissions);
    this.dualControl = new Set(doc.dual_control_permissions);
  }

  kind(name: ActionKindName): ActionKind | undefined {
    return this.kinds.get(name);
  }

  /** Every declared kind, in the generated order (sorted by kind). */
  allKinds(): readonly ActionKind[] {
    return this.doc.action_kinds;
  }

  roleGrants(role: Role, permission: Permission): boolean {
    return this.rolePermissions.get(role)?.has(permission) ?? false;
  }

  knownRole(role: Role): boolean {
    return this.rolePermissions.has(role);
  }

  agentHolds(permission: Permission): boolean {
    return this.agentPermissions.has(permission);
  }

  isDualControl(permission: Permission): boolean {
    return this.dualControl.has(permission);
  }

  surface(id: string): Surface | undefined {
    return this.doc.surfaces.find((s) => s.id === id);
  }

  killSwitchKind(kind: string): KillSwitchKind | undefined {
    return this.doc.kill_switch_kinds.find((k) => k.kind === kind);
  }

  gateAction(action: string): GateAction | undefined {
    return this.doc.gate_actions.find((a) => a.action === action);
  }
}

/** Fetches and validates the document in a browser. */
export async function fetchAuthority(base = ""): Promise<AuthorityIndex> {
  const res = await fetch(`${base}/generated/authority.json`, { cache: "no-store" });
  if (!res.ok) {
    throw new Error(`authority document could not be loaded (HTTP ${res.status})`);
  }
  return new AuthorityIndex(parseAuthority(await res.json()));
}
