/**
 * Replays every decision vector generated by `internal/adminplane` through the
 * console's own copy of the logic.
 *
 * This is the test that makes the copy safe. The Go integration suite proves
 * `adminplane.Decide` agrees with `internal/admin` and the database on every
 * one of these shapes; this proves `decide()` agrees with `adminplane.Decide`.
 *
 * Regenerate the vectors with:
 *   go test ./internal/adminplane -run TestDecisionVectorsGolden -update-vectors
 */
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

import { AuthorityIndex, parseAuthority } from "./authority.ts";
import type { Verb } from "./decide.ts";
import { decide, decideProposal, elevationOf, isUserId } from "./decide.ts";
import type { DecideAction, DecidePrincipal } from "./decide.ts";

const here = path.dirname(fileURLToPath(import.meta.url));

interface VectorPrincipal {
  subject_id: string;
  actor_type: string;
  roles: string[];
  auth_time?: string;
  amr: string[];
  break_glass_until?: string;
  absent?: boolean;
}

interface VectorAction {
  kind: string;
  status: string;
  requires_dual: boolean;
  proposed_by: string;
  approved_by?: string;
  target_id?: string;
  expires_at: string;
}

interface VectorWant {
  verb: string;
  allowed: boolean;
  reason: string;
  code?: string;
  permission?: string;
  permissions?: string[];
  step_up_max_age_seconds?: number;
}

interface VectorCase {
  principal: string;
  action: string;
  now: string;
  verb: string;
  want: VectorWant;
}

interface VectorDoc {
  version: number;
  principals: Record<string, VectorPrincipal>;
  actions: Record<string, VectorAction>;
  cases: VectorCase[];
}

function readJson<T>(rel: string): T {
  return JSON.parse(fs.readFileSync(path.join(here, rel), "utf8")) as T;
}

const index = new AuthorityIndex(parseAuthority(readJson("./generated/authority.json")));
const vectors = readJson<VectorDoc>("./generated/decisions.json");

function toPrincipal(v: VectorPrincipal): DecidePrincipal {
  return {
    ...(v.absent ? { absent: true } : {}),
    subjectId: v.subject_id ?? "",
    actorType: v.actor_type ?? "",
    roles: v.roles ?? [],
    authTime: v.auth_time ?? null,
    amr: v.amr ?? [],
    breakGlassUntil: v.break_glass_until ?? null,
    ...(v.actor_type === "AGENT" ? { accountIds: ["acct-1"] } : {}),
  };
}

function toAction(v: VectorAction): DecideAction {
  return {
    kind: v.kind,
    status: v.status,
    requiresDual: v.requires_dual,
    proposedBy: v.proposed_by,
    approvedBy: v.approved_by ?? null,
    ...(v.target_id === undefined ? {} : { targetId: v.target_id }),
    expiresAt: v.expires_at,
  };
}

/** The console's Decision in the wire shape the vectors record. */
function wireShape(d: ReturnType<typeof decide>): VectorWant {
  return {
    verb: d.verb,
    allowed: d.allowed,
    reason: d.reason,
    ...(d.code === undefined ? {} : { code: d.code }),
    ...(d.permission === undefined ? {} : { permission: d.permission }),
    ...(d.permissions === undefined ? {} : { permissions: [...d.permissions] }),
    ...(d.stepUpMaxAgeSeconds === undefined ? {} : { step_up_max_age_seconds: d.stepUpMaxAgeSeconds }),
  };
}

test("the vector file is the one this console was built against", () => {
  assert.equal(vectors.version, index.doc.version);
  assert.ok(vectors.cases.length > 0, "no vectors");
  assert.ok(Object.keys(vectors.principals).length >= 10, "too few principal shapes to be a real matrix");
});

test("every generated decision vector reproduces exactly", () => {
  let checked = 0;
  const byReason = new Map<string, number>();
  for (const c of vectors.cases) {
    const pv = vectors.principals[c.principal];
    const av = vectors.actions[c.action];
    assert.ok(pv, `unknown principal ${c.principal}`);
    assert.ok(av, `unknown action ${c.action}`);
    const principal = toPrincipal(pv);
    const action = toAction(av);
    const now = new Date(c.now);
    const got =
      c.verb === "propose"
        ? decideProposal(principal, action.kind, now, index)
        : decide(principal, action, c.verb as Verb, now, index);
    assert.deepEqual(
      wireShape(got),
      c.want,
      `${c.principal} | ${c.action} | ${c.verb} | ${c.now}`,
    );
    byReason.set(c.want.reason, (byReason.get(c.want.reason) ?? 0) + 1);
    checked++;
  }
  // A vector file in which nothing is ever permitted would pass against a
  // console that refuses everything, and prove nothing.
  assert.ok((byReason.get("ALLOWED") ?? 0) > 0, "no vector was ever allowed");
  assert.ok((byReason.get("SELF_APPROVAL") ?? 0) > 0, "no vector exercised self-approval");
  assert.ok((byReason.get("AGENT_PRINCIPAL") ?? 0) > 0, "no vector exercised an agent");
  assert.equal(checked, vectors.cases.length);
});

test("the proposer is never offered approval on their own action", () => {
  const now = new Date("2026-09-06T12:00:00Z");
  const proposer = "01a0754e-1111-7000-8000-000000000001";
  const principal: DecidePrincipal = {
    subjectId: proposer,
    actorType: "OPERATOR",
    roles: ["ADMIN", "BREAK_GLASS"],
    authTime: "2026-09-06T11:59:00Z",
    amr: ["mfa"],
    breakGlassUntil: "2026-09-06T13:00:00Z",
  };
  for (const kind of index.allKinds()) {
    if (!kind.requires_dual) continue;
    const action: DecideAction = {
      kind: kind.kind,
      status: "PROPOSED",
      requiresDual: true,
      proposedBy: proposer,
      approvedBy: null,
      expiresAt: "2026-09-07T12:00:00Z",
    };
    const d = decide(principal, action, "approve", now, index);
    assert.equal(d.allowed, false, `${kind.kind} offered self-approval`);
    assert.equal(d.reason, "SELF_APPROVAL");
  }
});

test("an elevation with an unknown deadline is offered but flagged", () => {
  const now = new Date("2026-09-06T12:00:00Z");
  const principal: DecidePrincipal = {
    subjectId: "01a0754e-2222-7000-8000-000000000002",
    actorType: "OPERATOR",
    roles: ["ADMIN", "BREAK_GLASS"],
    authTime: "2026-09-06T11:59:00Z",
    amr: ["mfa"],
    breakGlassUntil: "unknown",
  };
  assert.equal(elevationOf(principal, now), "UNKNOWN_DEADLINE");
  const kind = index.allKinds().find((k) => k.requires_break_glass_approval);
  assert.ok(kind, "no kind needs a break-glass approval");
  const action: DecideAction = {
    kind: kind.kind,
    status: "PROPOSED",
    requiresDual: true,
    proposedBy: "01a0754e-1111-7000-8000-000000000001",
    approvedBy: null,
    expiresAt: "2026-09-07T12:00:00Z",
  };
  const d = decide(principal, action, "approve", now, index);
  assert.equal(d.allowed, true);
  assert.equal(d.elevationUnverified, true, "an unverifiable elevation must be flagged, never presented as certain");

  // With a known, live deadline nothing is flagged.
  const known = decide({ ...principal, breakGlassUntil: "2026-09-06T13:00:00Z" }, action, "approve", now, index);
  assert.equal(known.allowed, true);
  assert.equal(known.elevationUnverified, undefined);
});

test("an elevation is dead at its deadline, not after it", () => {
  const deadline = "2026-09-06T12:00:00Z";
  const base: DecidePrincipal = {
    subjectId: "01a0754e-2222-7000-8000-000000000002",
    actorType: "OPERATOR",
    roles: ["ADMIN", "BREAK_GLASS"],
    authTime: null,
    amr: ["mfa"],
    breakGlassUntil: deadline,
  };
  const kind = index.allKinds().find((k) => k.requires_break_glass_approval);
  assert.ok(kind);
  const action: DecideAction = {
    kind: kind.kind,
    status: "PROPOSED",
    requiresDual: true,
    proposedBy: "01a0754e-1111-7000-8000-000000000001",
    approvedBy: null,
    expiresAt: "2026-09-08T12:00:00Z",
  };
  const at = (iso: string) => {
    const now = new Date(iso);
    const principal = { ...base, authTime: new Date(now.getTime() - 60_000).toISOString() };
    return { state: elevationOf(principal, now), decision: decide(principal, action, "approve", now, index) };
  };

  const before = at("2026-09-06T11:59:59Z");
  assert.equal(before.state, "ACTIVE");
  assert.equal(before.decision.allowed, true, "one second before the deadline the elevation still counts");

  // Liveness is `now < until`: the deadline instant itself is already gone.
  for (const iso of [deadline, "2026-09-06T12:00:01Z", "2026-09-06T13:00:00Z"]) {
    const got = at(iso);
    assert.equal(got.state, "EXPIRED", `elevation was still live at ${iso}`);
    assert.equal(got.decision.allowed, false, `an expired elevation was honoured at ${iso}`);
    assert.equal(got.decision.reason, "MISSING_PERMISSION");
  }
});

test("a session carrying a role the matrix does not know holds nothing", () => {
  const now = new Date("2026-09-06T12:00:00Z");
  const tampered: DecidePrincipal = {
    subjectId: "01a0754e-2222-7000-8000-000000000002",
    actorType: "OPERATOR",
    roles: ["ADMIN", "WIZARD"],
    authTime: "2026-09-06T11:59:00Z",
    amr: ["mfa"],
    breakGlassUntil: null,
  };
  const action: DecideAction = {
    kind: "KILL_SWITCH_RELEASE",
    status: "PROPOSED",
    requiresDual: true,
    proposedBy: "01a0754e-1111-7000-8000-000000000001",
    approvedBy: null,
    expiresAt: "2026-09-08T12:00:00Z",
  };
  for (const verb of ["approve", "reject", "execute", "cancel"] as const) {
    const d = decide(tampered, action, verb, now, index);
    assert.equal(d.allowed, false, verb);
    assert.equal(d.reason, "INVALID_PRINCIPAL", verb);
  }
});

test("isUserId matches the canonical UUID rule", () => {
  assert.equal(isUserId("01a0754e-514d-7afc-b119-e7ee00c4912c"), true);
  assert.equal(isUserId("dev:admin"), false);
  assert.equal(isUserId(""), false);
  assert.equal(isUserId("00000000-0000-0000-0000-000000000000"), false);
  assert.equal(isUserId("01a0754e514d7afcb119e7ee00c4912c"), false);
});
