package strategy

import (
	"fmt"
	"strings"

	"github.com/nodal/controlplane/internal/strategy/ir"
)

// Render produces the human-visible compiled form the owner must accept
// before a version can be bound to an agent (STRATEGY_IR.md §4).
//
// The English is generated by this code from the validated document, never
// by the model. A model-written summary could describe a strategy that
// differs from the one that will run, and the owner would be approving the
// description rather than the behavior. Everything here is derived from the
// IR, so the rendering cannot disagree with what executes.
//
// It is deterministic: the same document renders byte-identically.
func Render(doc *ir.IR) (string, error) {
	if doc == nil {
		return "", ir.ErrNilIR
	}
	var b strings.Builder

	fmt.Fprintf(&b, "Strategy %s, version %d\n", doc.StrategyID, doc.Version)
	if len(doc.Hash) > 0 {
		fmt.Fprintf(&b, "Semantic hash: %s\n", doc.Hash)
	}
	fmt.Fprintf(&b, "Risk policy: %s\n", doc.RiskPolicy.Version)
	b.WriteString("\n")

	b.WriteString("WHEN THIS RUNS\n")
	for _, t := range doc.Triggers {
		switch t.Kind {
		case ir.TriggerOnInterval:
			every := int64(0)
			if t.EveryMS != nil {
				every = *t.EveryMS
			}
			fmt.Fprintf(&b, "  - every %s (%s)\n", duration(every), t.Name)
		case ir.TriggerOnEvent:
			fmt.Fprintf(&b, "  - on each %s event (%s)\n", t.EventType, t.Name)
			if t.Filter != nil {
				fmt.Fprintf(&b, "      only when %s\n", renderExpr(t.Filter))
			}
		}
		if t.DedupWindowMS > 0 {
			fmt.Fprintf(&b, "      repeat firings within %s are ignored\n", duration(t.DedupWindowMS))
		}
	}
	fmt.Fprintf(&b, "  At most %d runs per minute.\n\n", doc.Envelope.MaxRunsPerMinute)

	b.WriteString("WHAT IT READS\n")
	for _, d := range doc.Dependencies {
		required := "optional"
		if d.Required {
			required = "required"
		}
		fmt.Fprintf(&b, "  - %s: %s data from tool %s v%d, no older than %s (%s)\n",
			d.Name, strings.ToLower(string(d.Kind)), d.ToolCode, d.ToolVersion, duration(d.MaxAgeMS), required)
		for _, k := range sortedKeys(d.Params) {
			fmt.Fprintf(&b, "      %s = %s\n", k, d.Params[k])
		}
	}
	b.WriteString("\n")

	if len(doc.Signals) > 0 {
		b.WriteString("WHAT IT COMPUTES\n")
		for _, s := range doc.Signals {
			fmt.Fprintf(&b, "  - %s = %s\n", s.Name, renderExpr(&s.Expr))
		}
		b.WriteString("\n")
	}

	if len(doc.Conditions) > 0 {
		b.WriteString("CONDITIONS\n")
		for _, c := range doc.Conditions {
			fmt.Fprintf(&b, "  - %s holds when %s\n", c.Name, renderExpr(&c.Expr))
		}
		b.WriteString("\n")
	}

	b.WriteString("WHAT IT DOES\n")
	for _, a := range doc.Actions {
		when := "always"
		if a.When != nil {
			when = "when " + string(*a.When)
		}
		switch a.Kind {
		case ir.ActionCallModel:
			fmt.Fprintf(&b, "  - %s: ask the model for a %s judgement (%s)\n", a.Name, a.Model.OutputSchema, when)
		case ir.ActionCommitPrediction:
			p := a.Prediction
			fmt.Fprintf(&b, "  - %s: record a prediction that %s goes %s over %s (%s)\n",
				a.Name, p.Instrument, strings.ToLower(string(p.Direction)), duration(p.HorizonMS), when)
		case ir.ActionCreateTradeIntent:
			in := a.Intent
			fmt.Fprintf(&b, "  - %s: propose to %s %s %s (%s)\n",
				a.Name, humanAction(string(in.Action)), in.Instrument, renderSizing(in.Sizing), when)
			fmt.Fprintf(&b, "      limits: slippage %d bps, fee %d bps, price impact %d bps; quote at most %s old\n",
				in.Constraints.MaxSlippageBPS, in.Constraints.MaxFeeBPS, in.Constraints.MaxPriceImpactBPS, duration(in.Constraints.QuoteFreshnessMS))
			if len(in.Constraints.AllowedVenues) > 0 {
				fmt.Fprintf(&b, "      venues: %s\n", strings.Join(in.Constraints.AllowedVenues, ", "))
			}
			fmt.Fprintf(&b, "      requires the prediction from %s to be committed first\n", in.Prediction)
		}
	}
	b.WriteString("\n")

	b.WriteString("LIMITS\n")
	fmt.Fprintf(&b, "  - needs at least %s allocated; no single trade above %s; no position above %s\n",
		doc.Envelope.MinAllocation, doc.Envelope.MaxSingleTrade, doc.Envelope.MaxPosition)
	if doc.Envelope.MaxDailyLoss.IsPositive() {
		fmt.Fprintf(&b, "  - stops for the day after losing %s\n", doc.Envelope.MaxDailyLoss)
	}
	fmt.Fprintf(&b, "  - at most %d trade proposals per hour\n", doc.Envelope.MaxIntentsPerHour)
	fmt.Fprintf(&b, "  - data budget: %d tool calls per run, %d per day, at most %s per day\n",
		doc.DataBudget.MaxToolCallsPerRun, doc.DataBudget.MaxToolCallsPerDay, doc.DataBudget.MaxSpendPerDay)
	if doc.ModelBudget.MaxCallsPerRun > 0 {
		fmt.Fprintf(&b, "  - model budget: %d calls per run, %d per day, at most %s per day\n",
			doc.ModelBudget.MaxCallsPerRun, doc.ModelBudget.MaxCallsPerDay, doc.ModelBudget.MaxSpendPerDay)
	}
	b.WriteString("\n")

	b.WriteString("WHAT IT IS ALLOWED TO DO\n")
	for _, e := range doc.Effects {
		fmt.Fprintf(&b, "  - %s: %s\n", e, effectProse(e))
	}
	b.WriteString("\nIt cannot move funds, sign transactions, change risk limits, change capital,\n")
	b.WriteString("call arbitrary programs, reach arbitrary network destinations, or read secrets.\n")
	b.WriteString("Every trade proposal is checked again by eligibility, risk, capital and\n")
	b.WriteString("settlement before anything executes.\n")

	return b.String(), nil
}

// effectProse states each capability in the owner's terms.
func effectProse(e ir.Effect) string {
	switch e {
	case ir.EffectReadMarketData:
		return "read market prices and derived features"
	case ir.EffectReadOnchainData:
		return "read on-chain events and wallet activity"
	case ir.EffectReadApprovedSocialData:
		return "read approved social data sources"
	case ir.EffectReadWalletIntelligence:
		return "read wallet intelligence scores"
	case ir.EffectCallModel:
		return "ask a language model for a structured judgement"
	case ir.EffectCommitPrediction:
		return "record a prediction before proposing a trade"
	case ir.EffectCreateTradeIntent:
		return "propose a trade for the platform to check and execute"
	}
	return string(e)
}

func humanAction(a string) string {
	switch a {
	case "ACQUIRE_NOTIONAL":
		return "buy"
	case "REDUCE_NOTIONAL":
		return "reduce"
	case "CLOSE_POSITION":
		return "close the position in"
	case "TARGET_EXPOSURE":
		return "hold a target exposure in"
	}
	return strings.ToLower(a)
}

func renderSizing(s ir.Sizing) string {
	switch s.Kind {
	case ir.SizingFixedNotional:
		if s.NotionalUSD != nil {
			return "for " + s.NotionalUSD.String()
		}
	case ir.SizingEnvelopeFractionBPS:
		if s.FractionBPS != nil {
			return fmt.Sprintf("for %s of the allocated capital", bpsPercent(int64(*s.FractionBPS)))
		}
	case ir.SizingTargetExposure:
		if s.TargetUSD != nil {
			return "up to " + s.TargetUSD.String()
		}
	case ir.SizingNone:
		return "entirely"
	}
	return "(unspecified size)"
}

// bpsPercent renders basis points as a percentage without floating point.
func bpsPercent(bps int64) string {
	whole := bps / 100
	frac := bps % 100
	if frac < 0 {
		frac = -frac
	}
	if frac == 0 {
		return fmt.Sprintf("%d%%", whole)
	}
	return fmt.Sprintf("%d.%02d%%", whole, frac)
}

// duration renders milliseconds in the largest exact unit, so a reader sees
// "5 minutes" rather than "300000 ms".
func duration(ms int64) string {
	if ms == 0 {
		return "0 ms"
	}
	units := []struct {
		size int64
		one  string
		many string
	}{
		{86_400_000, "day", "days"},
		{3_600_000, "hour", "hours"},
		{60_000, "minute", "minutes"},
		{1_000, "second", "seconds"},
	}
	for _, u := range units {
		if ms%u.size == 0 {
			n := ms / u.size
			if n == 1 {
				return "1 " + u.one
			}
			return fmt.Sprintf("%d %s", n, u.many)
		}
	}
	return fmt.Sprintf("%d ms", ms)
}

// renderExpr renders an expression as infix text.
func renderExpr(e *ir.Expr) string {
	if e == nil {
		return "(missing)"
	}
	switch {
	case e.Const != nil:
		return e.Const.String()
	case e.Field != nil:
		return string(e.Field.Dependency) + "." + e.Field.Path
	case e.Signal != nil:
		return string(*e.Signal)
	case e.Bin != nil:
		return "(" + renderExpr(e.Bin.L) + " " + binSymbol(e.Bin.Op) + " " + renderExpr(e.Bin.R) + ")"
	case e.Window != nil:
		return fmt.Sprintf("%s of %s.%s over the last %s",
			windowProse(e.Window.Fn), e.Window.Dependency, e.Window.Path, duration(e.Window.LookbackMS))
	case e.Cmp != nil:
		return renderExpr(e.Cmp.L) + " " + cmpSymbol(e.Cmp.Op) + " " + renderExpr(e.Cmp.R)
	case e.And != nil:
		return "(" + joinExprs(e.And, " and ") + ")"
	case e.Or != nil:
		return "(" + joinExprs(e.Or, " or ") + ")"
	case e.Not != nil:
		return "not (" + renderExpr(e.Not) + ")"
	}
	return "(empty)"
}

func joinExprs(list []*ir.Expr, sep string) string {
	parts := make([]string, 0, len(list))
	for _, e := range list {
		parts = append(parts, renderExpr(e))
	}
	return strings.Join(parts, sep)
}

func binSymbol(op ir.BinOpKind) string {
	switch op {
	case ir.OpAdd:
		return "+"
	case ir.OpSub:
		return "-"
	case ir.OpMul:
		return "*"
	case ir.OpDiv:
		return "/"
	case ir.OpMin:
		return "min"
	case ir.OpMax:
		return "max"
	}
	return string(op)
}

func cmpSymbol(op ir.CmpOp) string {
	switch op {
	case ir.CmpLT:
		return "<"
	case ir.CmpLE:
		return "<="
	case ir.CmpGT:
		return ">"
	case ir.CmpGE:
		return ">="
	case ir.CmpEQ:
		return "=="
	case ir.CmpNE:
		return "!="
	}
	return string(op)
}

func windowProse(fn ir.WindowFn) string {
	switch fn {
	case ir.WinSMA:
		return "the simple moving average"
	case ir.WinEMA:
		return "the exponential moving average"
	case ir.WinMax:
		return "the maximum"
	case ir.WinMin:
		return "the minimum"
	case ir.WinSum:
		return "the sum"
	case ir.WinCount:
		return "the count"
	case ir.WinReturn:
		return "the return"
	case ir.WinStddev:
		return "the standard deviation"
	}
	return string(fn)
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	// sort.Strings via the ir helper keeps one ordering rule in the codebase.
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j] < out[j-1]; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}
