<#
.SYNOPSIS
  Everything between a working role session and a Terraform plan, in one
  command.

.DESCRIPTION
  Bootstraps the state bucket if it does not exist, writes backend.hcl, runs
  init, and then plan. Every step is idempotent, so running it twice is safe and
  running it after a failure resumes rather than restarts.

  It stops before `apply` unless -Apply is given, because an apply spends money
  and creates things that then have to be destroyed.

.PARAMETER Environment
  Which environment under infra/terraform/environments. Defaults to prod, which
  is where Path B lives.

.PARAMETER Apply
  Run apply after the plan. Without it, the plan is printed and nothing changes.

.EXAMPLE
  .\scripts\aws\nodal-deploy.ps1
.EXAMPLE
  .\scripts\aws\nodal-deploy.ps1 -Apply
#>
[CmdletBinding()]
param(
    [string]$Environment = 'prod',
    [switch]$Apply
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Import-Module (Join-Path $PSScriptRoot 'NodalAws.psm1') -Force
$cfg = Get-NodalConfig

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$envDir = Join-Path $repoRoot "infra\terraform\environments\$Environment"
if (-not (Test-Path -LiteralPath $envDir)) { throw "No such environment: $envDir" }

$bucket = "nodal-terraform-state-$($cfg.AccountId)-$($cfg.Region)"
$tf = Join-Path $PSScriptRoot 'nodal-tf.ps1'

Write-Host ''
Write-Host "Nodal deploy -- environments/$Environment" -ForegroundColor White
Write-Host ''

# --- the session ------------------------------------------------------------
$session = Get-NodalSession
if (-not $session) {
    Write-Bad 'no live role session'
    Write-Host '  Run .\scripts\aws\nodal-login.ps1 (one MFA code) and try again.' -ForegroundColor Yellow
    exit 3
}
Assert-RoleIdentity -Arn $session.Arn

# Every AWS call below runs as the role, through the credential_process profile.
# Nothing here re-assumes anything and nothing prompts.
$P = @('--profile', $cfg.RoleProf, '--region', $cfg.Region)

# --- 1. the state bucket ----------------------------------------------------
# Terraform cannot create the bucket that holds its own state, so this is the
# one piece of infrastructure made with the CLI. Each call is checked first, so
# a partially-created bucket is completed rather than rejected.
Write-Step "checking the state bucket $bucket"
$head = Invoke-AwsQuiet (@('s3api', 'head-bucket', '--bucket', $bucket) + $P)
if ($head.Ok) {
    Write-Ok 'state bucket exists'
} else {
    Write-Step 'creating the state bucket'
    $create = Invoke-AwsQuiet (@('s3api', 'create-bucket', '--bucket', $bucket,
        '--create-bucket-configuration', "LocationConstraint=$($cfg.Region)") + $P)
    if (-not $create.Ok) {
        Write-Bad "could not create $bucket"
        Write-Host ($create.Output | Out-String) -ForegroundColor DarkGray
        exit 4
    }
    Write-Ok 'state bucket created'
}

# Versioning is not decoration here: it is the only way back from a truncated or
# corrupted state file, and a corrupted state file is the one failure that can
# orphan every resource in the account.
Write-Step 'enforcing versioning, encryption and public-access block'
[void](Invoke-AwsQuiet (@('s3api', 'put-bucket-versioning', '--bucket', $bucket,
    '--versioning-configuration', 'Status=Enabled') + $P))
[void](Invoke-AwsQuiet (@('s3api', 'put-public-access-block', '--bucket', $bucket,
    '--public-access-block-configuration',
    'BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true') + $P))
[void](Invoke-AwsQuiet (@('s3api', 'put-bucket-encryption', '--bucket', $bucket,
    '--server-side-encryption-configuration',
    '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"},"BucketKeyEnabled":true}]}') + $P))

# Read the settings back rather than trusting the writes. A bucket that silently
# lost versioning looks identical to one that has it.
$ver = Invoke-AwsQuiet (@('s3api', 'get-bucket-versioning', '--bucket', $bucket, '--query', 'Status', '--output', 'text') + $P)
$verState = ($ver.Output | Out-String).Trim()
if ($verState -ne 'Enabled') {
    Write-Bad "state bucket versioning is '$verState', not Enabled"
    exit 4
}
Write-Ok 'state bucket: versioned, encrypted, private'

# --- 2. backend.hcl ---------------------------------------------------------
# Generated rather than copied, because the account id and region are already
# known here and a hand-edited backend is a state file in the wrong bucket.
$backend = Join-Path $envDir 'backend.hcl'
$lines = @(
    '# GENERATED by scripts/aws/nodal-deploy.ps1. Do not edit by hand.',
    "bucket       = `"$bucket`"",
    "key          = `"environments/$Environment/terraform.tfstate`"",
    "region       = `"$($cfg.Region)`"",
    'use_lockfile = true'
)
Write-PlainFile -Path $backend -Lines $lines
Write-Ok "backend.hcl -> s3://$bucket/environments/$Environment/terraform.tfstate"

# --- 3. tfvars --------------------------------------------------------------
# Never generated. It carries the hostname, the certificate and the identity
# provider, and inventing any of those would produce a deployment that applies
# and does not work.
$tfvars = Join-Path $envDir 'terraform.tfvars'
if (-not (Test-Path -LiteralPath $tfvars)) {
    Write-Action -Title 'fill in terraform.tfvars' -Detail @(
        "Copy the Path B example and complete the values marked CHANGE ME:",
        "  copy `"$envDir\terraform.tfvars.pathb.example`" `"$tfvars`"",
        '',
        'It needs the ACM certificate ARN, the Auth0 issuer and client id, and',
        'the alert email addresses. Everything else is already filled in.'
    )
    exit 5
}
Write-Ok 'terraform.tfvars present'

# --- 4. init ----------------------------------------------------------------
Write-Step 'terraform init'
& $tf 'init' -Environment $Environment -TfArgs @('-backend-config=backend.hcl', '-input=false')
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

# --- 5. plan ----------------------------------------------------------------
Write-Step 'terraform plan'
& $tf 'plan' -Environment $Environment -TfArgs @('-input=false', '-out=tfplan')
if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

if (-not $Apply) {
    Write-Host ''
    Write-Host '  Plan written to tfplan. Nothing has been created.' -ForegroundColor Green
    Write-Host '  Review it, then: .\scripts\aws\nodal-deploy.ps1 -Apply' -ForegroundColor Green
    Write-Host ''
    exit 0
}

Write-Step 'terraform apply'
& $tf 'apply' -Environment $Environment -TfArgs @('-input=false', 'tfplan')
exit $LASTEXITCODE
