/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts owned by the caller */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accounts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                403: components["responses"]["Problem"];
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity timeline (event → prediction → intent → eligibility → risk → execution → fill → reconciliation) */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path: {
                    accountId: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of activity items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/buying-power": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Buying power computed now by the backend (PART 25); never cached as truth */
        get: {
            parameters: {
                query?: {
                    /** @description Which restrictions are blocking; figures are identical for every purpose */
                    purpose?: "DISPLAY" | "TRADE" | "WITHDRAWAL";
                };
                header?: never;
                path: {
                    accountId: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Buying power */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BuyingPower"];
                    };
                };
                403: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export journal transactions and fills as CSV or JSON (PART 202) */
        get: {
            parameters: {
                query?: {
                    format?: "csv" | "json";
                    from?: string;
                    to?: string;
                };
                header?: never;
                path: {
                    accountId: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Export document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, unknown>;
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/holdings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Holdings with units, USD mark, basis and unrealized P&L */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Holdings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HoldingsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}/ledger/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Journal transactions for the account (append-only history), newest first */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path: {
                    accountId: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of journal transactions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JournalTransactionPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search accounts (operator roles) */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accounts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountPage"];
                    };
                };
                403: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/accounts/{accountId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freeze / restrict / reactivate an account (reason required; audited; no balance editing exists) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    accountId: components["parameters"]["AccountId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AccountStatusChange"];
                };
            };
            responses: {
                /** @description Updated account */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Account"];
                    };
                };
                403: components["responses"]["Problem"];
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending and recent controlled administrative actions */
        get: {
            parameters: {
                query?: {
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Actions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminActionPage"];
                    };
                };
            };
        };
        put?: never;
        /** Propose a controlled action (reason required; step-up) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AdminActionProposal"];
                };
            };
            responses: {
                /** @description Proposed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminAction"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/actions/{actionId}/{decision}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve or reject a proposed action (approver ≠ proposer; step-up) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    actionId: components["schemas"]["UUID"];
                    decision: "approve" | "reject" | "execute";
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description Action after the decision */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminAction"];
                    };
                };
                403: components["responses"]["Problem"];
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/gates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Production capability gates for this environment */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CapabilityGate"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/gates/{capability}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose / approve / activate / suspend / resume / revoke a gate (dual control; step-up) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    action: "propose" | "approve" | "activate" | "suspend" | "resume" | "revoke";
                    capability: components["schemas"]["Capability"];
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GateActionRequest"];
                };
            };
            responses: {
                /** @description Gate after the transition */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CapabilityGate"];
                    };
                };
                403: components["responses"]["Problem"];
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/instruments/{instrumentId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change instrument status (ACTIVE / CLOSE_ONLY / RESTRICTED / HALTED / DELISTING / DELISTED) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    instrumentId: components["parameters"]["InstrumentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StatusChange"];
                };
            };
            responses: {
                /** @description Instrument */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Instrument"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/kill-switches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Active and inactive switches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KillSwitch"][];
                    };
                };
            };
        };
        put?: never;
        /** Activate (fast, single operator) or release (step-up; SEVERE needs an approved admin action) a kill switch */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["KillSwitchRequest"];
                };
            };
            responses: {
                /** @description Switch state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KillSwitch"];
                    };
                };
                403: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider health and verification labels */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Providers */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProviderStatus"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reconciliation/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    account_id?: components["schemas"]["UUID"];
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                    status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reconciliation records */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconciliationRecordPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/reconciliation/records/{recordId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a mismatch (reason + evidence; material resolutions require an approved admin action; corrections post a compensating journal transaction) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    recordId: components["schemas"]["UUID"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ReconciliationResolution"];
                };
            };
            responses: {
                /** @description Record after resolution */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconciliationRecord"];
                    };
                };
                403: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registered assets with chain, mint, decimals and safety status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Assets */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Asset"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC callback; establishes a server-side session cookie */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the application */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Problem"];
                401: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin OIDC login (authorization-code + PKCE); redirects to the identity provider */
        get: {
            parameters: {
                query?: {
                    /** @description Request strong authentication (MFA/passkey) for a sensitive action */
                    step_up?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Redirect to the identity provider */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                503: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Server-sent events for balances, orders, deposits and agent state (not authoritative) */
        get: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Resume cursor; on a gap the server sends a `resync` event and the client must refetch REST state */
                    "Last-Event-ID"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream of `Event` objects (`id`, `event`, `data` = JSON `StreamEvent`) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funding/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    account_id: components["schemas"]["UUID"];
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of deposits */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepositPage"];
                    };
                };
            };
        };
        put?: never;
        /** Start a fiat-to-USDC funding session (redirect success never credits money — PART 162) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["StartDepositRequest"];
                };
            };
            responses: {
                /** @description Idempotent replay */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Deposit"];
                    };
                };
                /** @description Deposit created with provider session */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Deposit"];
                    };
                };
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/funding/deposits/{depositId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    depositId: components["parameters"]["DepositId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deposit with transition history */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DepositDetail"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process is alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tradable instruments (V1 spot pairs) with status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Instruments */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Instrument"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instruments/{instrumentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    instrumentId: components["parameters"]["InstrumentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Instrument with venue listings */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InstrumentDetail"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Intents for an account, newest first */
        get: {
            parameters: {
                query: {
                    account_id: components["schemas"]["UUID"];
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of intents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TradeIntentPage"];
                    };
                };
            };
        };
        put?: never;
        /** Submit a typed trade intent (manual trading entry point; PART 35) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmitIntentRequest"];
                };
            };
            responses: {
                /** @description Idempotent replay of a previously accepted intent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TradeIntent"];
                    };
                };
                /** @description Intent accepted and processing */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TradeIntent"];
                    };
                };
                400: components["responses"]["Problem"];
                403: components["responses"]["Problem"];
                409: components["responses"]["Problem"];
                422: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intents/{intentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    intentId: components["parameters"]["IntentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Intent with its decisions, plan, order and fills */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TradeIntentDetail"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/intents/{intentId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request cancellation (CANCEL_REQUESTED; only external confirmation yields CANCELLED — PART 227) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    intentId: components["parameters"]["IntentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancellation requested */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TradeIntent"];
                    };
                };
                409: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current principal and the accounts it may act on */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Principal */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Principal"];
                    };
                };
                401: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    account_id: components["schemas"]["UUID"];
                    cursor?: components["parameters"]["Cursor"];
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Page of orders */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order with attempts and fills */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderDetail"];
                    };
                };
                404: components["responses"]["Problem"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quotes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Non-binding quote preview with full fee disclosure (no money moves, no reservation) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QuotePreviewRequest"];
                };
            };
            responses: {
                /** @description Quote disclosure */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuoteDisclosure"];
                    };
                };
                422: components["responses"]["Problem"];
                503: components["responses"]["Problem"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready when the database is reachable and configuration validated; never reports provider liveness as readiness */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's sessions (device listing) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sessions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SessionSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke one of the caller's sessions */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: components["parameters"]["SessionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["Problem"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build version and non-secret configuration hash (PART 222) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Version */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            build_version: string;
                            config_hash: string;
                            environment: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Provider webhook ingestion (signature-verified, persisted before processing, idempotent — PART 30) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    provider: "stripe";
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Record<string, unknown>;
                };
            };
            responses: {
                /** @description Acknowledged (including duplicates) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Signature or replay validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a withdrawal (requires step-up; the WITHDRAWALS capability is DISABLED in V1 — PART 94) */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WithdrawalRequest"];
                };
            };
            responses: {
                /** @description Withdrawal requested */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Withdrawal"];
                    };
                };
                403: components["responses"]["Problem"];
                /** @description CAPABILITY_NOT_APPROVED while the gate is disabled */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Account: {
            created_at: components["schemas"]["Timestamp"];
            id: components["schemas"]["UUID"];
            /** @enum {string} */
            kind: "CUSTOMER" | "CANARY" | "PLATFORM";
            /** @enum {string} */
            status: "ACTIVE" | "RESTRICTED" | "FROZEN" | "CLOSED";
            status_reason?: string;
        };
        AccountPage: components["schemas"]["Page"] & {
            items: components["schemas"]["Account"][];
        };
        AccountStatusChange: {
            reason: string;
            /** @enum {string} */
            to: "ACTIVE" | "RESTRICTED" | "FROZEN" | "CLOSED";
        };
        ActivityItem: {
            correlation_id?: string;
            detail?: {
                [key: string]: unknown;
            };
            id: string;
            /** @enum {string} */
            kind: "DATA_EVENT" | "PREDICTION" | "INTENT" | "ELIGIBILITY" | "RISK" | "PLAN" | "EXECUTION" | "FILL" | "RECONCILIATION" | "LEDGER" | "FUNDING" | "SECURITY";
            occurred_at: components["schemas"]["Timestamp"];
            references?: {
                [key: string]: string;
            };
            summary: string;
        };
        ActivityPage: components["schemas"]["Page"] & {
            items: components["schemas"]["ActivityItem"][];
        };
        AdminAction: {
            approved_at?: components["schemas"]["Timestamp"];
            approved_by?: components["schemas"]["UUID"];
            executed_at?: components["schemas"]["Timestamp"];
            expires_at: components["schemas"]["Timestamp"];
            id: components["schemas"]["UUID"];
            kind: string;
            params?: {
                [key: string]: unknown;
            };
            params_hash?: string;
            proposed_at: components["schemas"]["Timestamp"];
            proposed_by: components["schemas"]["UUID"];
            reason?: string;
            requires_dual: boolean;
            /** @enum {string} */
            status: "PROPOSED" | "APPROVED" | "REJECTED" | "EXECUTED" | "FAILED" | "EXPIRED" | "CANCELLED";
            target_id: string;
            target_type: string;
        };
        AdminActionPage: components["schemas"]["Page"] & {
            items: components["schemas"]["AdminAction"][];
        };
        AdminActionProposal: {
            kind: string;
            params?: {
                [key: string]: unknown;
            };
            reason: string;
            target_id: string;
            target_type: string;
        };
        Asset: {
            chain: string;
            decimals: number;
            id: components["schemas"]["UUID"];
            is_stablecoin: boolean;
            /** @enum {string} */
            kind: "NATIVE" | "SPL_TOKEN" | "SPL_TOKEN_2022" | "FIAT";
            mint_address: string;
            name: string;
            peg_currency?: string;
            risk_class: string;
            /** @enum {string} */
            status: "ACTIVE" | "CLOSE_ONLY" | "RESTRICTED" | "HALTED" | "DELISTING" | "DELISTED";
            symbol: string;
            token_extensions?: string[];
        };
        /** @description Basis points; 10000 == 100% */
        BPS: number;
        BuyingPower: {
            as_of: components["schemas"]["Timestamp"];
            available_now: components["schemas"]["USD"];
            buying_power: components["schemas"]["USD"];
            haircuts: {
                asset: components["schemas"]["UUID"];
                factor_bps: components["schemas"]["BPS"];
                reason: string;
            }[];
            pending: components["schemas"]["USD"];
            policy_version: string;
            portfolio_value: components["schemas"]["USD"];
            /** @enum {string} */
            purpose: "DISPLAY" | "TRADE" | "WITHDRAWAL" | "AGENT_DEPLOY";
            reserved: components["schemas"]["USD"];
            restrictions: {
                asset?: components["schemas"]["UUID"];
                blocking: boolean;
                code: string;
                detail: string;
                /** @enum {string} */
                scope: "ACCOUNT" | "WITHDRAWAL" | "ASSET";
            }[];
            underlying_balances: {
                asset: components["schemas"]["UUID"];
                decimals: number;
                price_ref: string;
                quantity: components["schemas"]["Quantity"];
                status: string;
                symbol: string;
                usd_value: components["schemas"]["USD"];
            }[];
            withdrawable: components["schemas"]["USD"];
        };
        /** @enum {string} */
        Capability: "LIVE_FUNDING" | "LIVE_MANUAL_TRADING" | "LIVE_AGENT_TRADING" | "WITHDRAWALS" | "SOCIAL_DATA_PERSISTENCE" | "MARKETPLACE" | "CROSS_CHAIN" | "PREDICTION_MARKETS" | "SECURITIES" | "CEX_TRADING";
        CapabilityGate: {
            /** @description Result of the five-condition activation check, not just the row state */
            active: boolean;
            approval_version: number;
            approvers?: {
                [key: string]: unknown;
            }[];
            capability: components["schemas"]["Capability"];
            effective_at?: components["schemas"]["Timestamp"];
            environment: string;
            expires_at?: components["schemas"]["Timestamp"];
            inactive_reason?: string;
            legal_review_ref?: string;
            provider_contract_ref?: string;
            risk_approval_ref?: string;
            security_approval_ref?: string;
            /** @enum {string} */
            state: "DISABLED" | "PENDING_APPROVAL" | "APPROVED" | "ACTIVE" | "SUSPENDED" | "REVOKED" | "EXPIRED";
        };
        Decision: {
            decision: string;
            evaluated_at: components["schemas"]["Timestamp"];
            id: components["schemas"]["UUID"];
            policy_version: string;
            reason_codes: string[];
        };
        Deposit: {
            account_id: components["schemas"]["UUID"];
            available_at?: components["schemas"]["Timestamp"];
            buying_power_eligible: boolean;
            /** @description Provider client secret for the embedded/hosted onramp UI, returned once at creation */
            client_secret_ref?: string;
            created_at: components["schemas"]["Timestamp"];
            expected_asset: components["schemas"]["UUID"];
            expected_quantity?: components["schemas"]["Quantity"];
            fiat_amount?: string;
            fiat_currency?: string;
            id: components["schemas"]["UUID"];
            observed_quantity?: components["schemas"]["Quantity"];
            provider: string;
            provider_session_id?: string;
            reversible_until?: components["schemas"]["Timestamp"];
            /** @enum {string} */
            status: "CREATED" | "SESSION_CREATED" | "CUSTOMER_ACTION_REQUIRED" | "PROVIDER_PROCESSING" | "PROVIDER_CONFIRMED" | "SETTLEMENT_OBSERVED" | "RECONCILED" | "AVAILABLE" | "FAILED" | "EXPIRED" | "CANCELLED" | "REVERSED" | "REVIEW_REQUIRED";
            tx_signature?: string;
            withdrawal_eligible: boolean;
        };
        DepositDetail: components["schemas"]["Deposit"] & {
            journal_transaction_id?: components["schemas"]["UUID"];
            transitions?: {
                from: string;
                occurred_at: components["schemas"]["Timestamp"];
                reason?: string;
                to: string;
            }[];
        };
        DepositPage: components["schemas"]["Page"] & {
            items: components["schemas"]["Deposit"][];
        };
        Fill: {
            external_fill_id: string;
            /** @enum {string} */
            finality: "OBSERVED" | "CONFIRMED" | "FINALIZED";
            id: components["schemas"]["UUID"];
            input_quantity: components["schemas"]["Quantity"];
            journal_transaction_id?: components["schemas"]["UUID"];
            network_fee_quantity?: components["schemas"]["Quantity"];
            observed_at: components["schemas"]["Timestamp"];
            output_quantity: components["schemas"]["Quantity"];
            platform_fee_quantity?: components["schemas"]["Quantity"];
            slot?: number;
            tx_signature?: string;
            venue: string;
            venue_fee_quantity?: components["schemas"]["Quantity"];
        };
        GateActionRequest: {
            effective_at?: components["schemas"]["Timestamp"];
            evidence_hashes?: string[];
            expires_at?: components["schemas"]["Timestamp"];
            legal_review_ref?: string;
            note?: string;
            provider_contract_ref?: string;
            reason: string;
            risk_approval_ref?: string;
            security_approval_ref?: string;
        };
        HoldingsResponse: {
            as_of: components["schemas"]["Timestamp"];
            holdings: {
                asset: components["schemas"]["UUID"];
                chain?: string;
                cost_basis_usd: components["schemas"]["USD"];
                decimals: number;
                /** @description custody location, e.g. embedded wallet address */
                location: string;
                mint_address?: string;
                price_ref?: string;
                quantity: components["schemas"]["Quantity"];
                realized_pnl_usd?: components["schemas"]["USD"];
                symbol: string;
                unrealized_pnl_usd: components["schemas"]["USD"];
                usd_mark: components["schemas"]["USD"];
            }[];
        };
        Instrument: {
            active_from: components["schemas"]["Timestamp"];
            active_until?: components["schemas"]["Timestamp"];
            base_asset?: components["schemas"]["UUID"];
            canonical_name: string;
            id: components["schemas"]["UUID"];
            quote_asset?: components["schemas"]["UUID"];
            risk_class: string;
            settlement_asset: components["schemas"]["UUID"];
            /** @enum {string} */
            status: "ACTIVE" | "CLOSE_ONLY" | "RESTRICTED" | "HALTED" | "DELISTING" | "DELISTED";
            /** @enum {string} */
            type: "SPOT_PAIR" | "EVENT_OUTCOME";
        };
        InstrumentDetail: components["schemas"]["Instrument"] & {
            base: components["schemas"]["Asset"];
            listings: components["schemas"]["VenueListing"][];
            quote: components["schemas"]["Asset"];
        };
        /** @enum {string} */
        IntentAction: "ACQUIRE_NOTIONAL" | "REDUCE_NOTIONAL" | "CLOSE_POSITION" | "TARGET_EXPOSURE";
        IntentConstraints: {
            allowed_venues?: string[];
            execution_deadline?: components["schemas"]["Timestamp"];
            max_fee_bps?: components["schemas"]["BPS"];
            max_price_impact_bps?: components["schemas"]["BPS"];
            max_slippage_bps?: components["schemas"]["BPS"];
            min_receive?: components["schemas"]["Quantity"];
            quote_freshness_ms?: number;
        };
        JournalTransaction: {
            content_hash: string;
            description?: string;
            effective_at: components["schemas"]["Timestamp"];
            entries: {
                account_code: string;
                asset: components["schemas"]["UUID"];
                quantity: components["schemas"]["Quantity"];
                seq: number;
                /** @enum {string} */
                side: "DEBIT" | "CREDIT";
                usd_value?: components["schemas"]["USD"];
            }[];
            id: components["schemas"]["UUID"];
            kind: string;
            posted_at: components["schemas"]["Timestamp"];
            reason_code?: string;
            reference: {
                id: string;
                type: string;
            };
            reversal_of?: components["schemas"]["UUID"];
        };
        JournalTransactionPage: components["schemas"]["Page"] & {
            items: components["schemas"]["JournalTransaction"][];
        };
        KillSwitch: {
            activated_at?: components["schemas"]["Timestamp"];
            active: boolean;
            /** @enum {string} */
            kind: "GLOBAL_NEW_RISK_KILL" | "ACCOUNT_FREEZE" | "AGENT_PAUSE" | "STRATEGY_VERSION_DISABLE" | "VENUE_DISABLE" | "INSTRUMENT_CLOSE_ONLY" | "INSTRUMENT_HALT" | "CHAIN_DISABLE_NEW_ACTIONS" | "PROVIDER_DISABLE_NEW_ACTIONS" | "FUNDING_DISABLE" | "WITHDRAWALS_DISABLE" | "MODEL_DISABLE";
            reason?: string;
            released_at?: components["schemas"]["Timestamp"];
            scope_id: string;
            /** @enum {string} */
            severity: "STANDARD" | "SEVERE";
        };
        KillSwitchRequest: {
            /** @enum {string} */
            action: "activate" | "release";
            /** @description Required to release a SEVERE switch */
            approval_id?: components["schemas"]["UUID"];
            kind: string;
            reason: string;
            /** @default * */
            scope_id: string;
        };
        Order: {
            account_id: components["schemas"]["UUID"];
            created_at: components["schemas"]["Timestamp"];
            filled_input_quantity: components["schemas"]["Quantity"];
            filled_output_quantity: components["schemas"]["Quantity"];
            id: components["schemas"]["UUID"];
            input_asset: components["schemas"]["UUID"];
            input_quantity: components["schemas"]["Quantity"];
            instrument_id: components["schemas"]["UUID"];
            intent_id: components["schemas"]["UUID"];
            min_output_quantity: components["schemas"]["Quantity"];
            mode: string;
            output_asset: components["schemas"]["UUID"];
            rejection_code?: string;
            /** @enum {string} */
            side: "BUY" | "SELL";
            /** @enum {string} */
            status: "CREATED" | "VALIDATED" | "CAPITAL_RESERVED" | "PLANNED" | "SUBMITTING" | "SUBMITTED" | "ACKNOWLEDGED" | "PARTIALLY_FILLED" | "FILLED" | "SETTLING" | "SETTLED" | "REJECTED" | "EXPIRED" | "CANCEL_REQUESTED" | "CANCELLED" | "SUBMISSION_UNKNOWN" | "RECONCILIATION_REQUIRED" | "FAILED_FINAL";
            terminal_at?: components["schemas"]["Timestamp"];
        };
        OrderDetail: components["schemas"]["Order"] & {
            attempts?: {
                attempt_no: number;
                confirmed_at?: components["schemas"]["Timestamp"];
                created_at: components["schemas"]["Timestamp"];
                finality?: string;
                finalized_at?: components["schemas"]["Timestamp"];
                id: components["schemas"]["UUID"];
                status: string;
                submitted_at?: components["schemas"]["Timestamp"];
                tx_signature?: string;
            }[];
            fills?: components["schemas"]["Fill"][];
        };
        OrderPage: components["schemas"]["Page"] & {
            items: components["schemas"]["Order"][];
        };
        Page: {
            next_cursor: string | null;
        };
        Principal: {
            account_ids: components["schemas"]["UUID"][];
            /** @enum {string} */
            actor_type: "USER" | "OPERATOR";
            amr: string[];
            auth_time: components["schemas"]["Timestamp"];
            roles: string[];
            step_up_valid_until?: components["schemas"]["Timestamp"];
            subject_id: components["schemas"]["UUID"];
        };
        Problem: {
            /** @description Stable machine-readable code (INSUFFICIENT_BUYING_POWER, ACCOUNT_FROZEN, ASSET_RESTRICTED, VENUE_UNAVAILABLE, QUOTE_EXPIRED, RISK_MAX_POSITION, RISK_DAILY_LOSS, ELIGIBILITY_JURISDICTION, CAPABILITY_NOT_APPROVED, SUBMISSION_STATE_UNKNOWN, RECONCILIATION_REQUIRED, PROVIDER_UNAVAILABLE, STALE_MARKET_DATA, INVALID_IDEMPOTENCY_REUSE, KILL_SWITCH_ACTIVE, NO_VALID_PLAN, …) */
            code: string;
            detail?: string;
            fields?: {
                [key: string]: unknown;
            };
            instance?: string;
            request_id?: string;
            status: number;
            title: string;
            type: string;
        };
        ProviderStatus: {
            disable_reason?: string;
            error_rate_bps?: number;
            /** @enum {string} */
            health: "HEALTHY" | "DEGRADED" | "UNHEALTHY" | "DISABLED";
            last_success_at?: components["schemas"]["Timestamp"];
            /** @enum {string} */
            mode?: "fake" | "sandbox" | "live";
            name: string;
            p95_ms?: number;
            role: string;
            /** @enum {string} */
            verification: "CODE_COMPLETE" | "CONTRACT_TESTED" | "SANDBOX_VERIFIED" | "CANARY_VERIFIED" | "LIVE_VERIFIED" | "BLOCKED_EXTERNAL";
        };
        /**
         * @description Exact asset base units as an integer string
         * @example 1500000000
         */
        Quantity: string;
        QuoteDisclosure: {
            /** @description decimal string, quote per base */
            effective_price?: string;
            expected_output: components["schemas"]["Quantity"];
            expires_at: components["schemas"]["Timestamp"];
            fee_policy_version?: string;
            input_asset: components["schemas"]["UUID"];
            input_quantity: components["schemas"]["Quantity"];
            minimum_output: components["schemas"]["Quantity"];
            network_fee_asset?: components["schemas"]["UUID"];
            network_fee_estimate: components["schemas"]["Quantity"];
            output_asset: components["schemas"]["UUID"];
            platform_fee: components["schemas"]["Quantity"];
            platform_fee_bps: components["schemas"]["BPS"];
            price_impact_bps: components["schemas"]["BPS"];
            provider: string;
            quote_id: components["schemas"]["UUID"];
            received_at: components["schemas"]["Timestamp"];
            route: {
                [key: string]: unknown;
            }[];
            slippage_bps: components["schemas"]["BPS"];
            total_estimated_cost_usd: components["schemas"]["USD"];
            venue: string;
            venue_fee: components["schemas"]["Quantity"];
            venue_fee_asset?: components["schemas"]["UUID"];
        };
        QuotePreviewRequest: {
            account_id: components["schemas"]["UUID"];
            action: components["schemas"]["IntentAction"];
            constraints?: components["schemas"]["IntentConstraints"];
            instrument_id: components["schemas"]["UUID"];
            notional_usd?: components["schemas"]["USD"];
            quantity?: components["schemas"]["Quantity"];
        };
        ReconciliationRecord: {
            account_id?: components["schemas"]["UUID"];
            asset_id?: components["schemas"]["UUID"];
            blocks_new_risk: boolean;
            compensating_journal_transaction_id?: components["schemas"]["UUID"];
            difference?: {
                [key: string]: unknown;
            };
            expected?: {
                [key: string]: unknown;
            };
            id: components["schemas"]["UUID"];
            /** @enum {string} */
            kind: "EXECUTION" | "WALLET_BALANCE" | "FUNDING" | "LEDGER_INTERNAL" | "POSITION_LEDGER" | "SUBMISSION_UNKNOWN";
            material: boolean;
            /** @enum {string} */
            mode: "EVENT_DRIVEN" | "PERIODIC" | "FULL";
            observed?: {
                [key: string]: unknown;
            };
            opened_at: components["schemas"]["Timestamp"];
            resolution_evidence_ref?: string;
            resolution_reason?: string;
            resolved_at?: components["schemas"]["Timestamp"];
            scope_id: string;
            scope_type: string;
            /** @enum {string} */
            status: "OPEN" | "MATCHED" | "MISMATCH" | "INVESTIGATING" | "RESOLVED_AUTOMATIC" | "RESOLVED_MANUAL" | "ESCALATED";
        };
        ReconciliationRecordPage: components["schemas"]["Page"] & {
            items: components["schemas"]["ReconciliationRecord"][];
        };
        ReconciliationResolution: {
            approval_id?: components["schemas"]["UUID"];
            /** @description Reason-coded compensating posting; never a balance edit */
            compensation?: {
                entries?: {
                    account_code: string;
                    asset: components["schemas"]["UUID"];
                    quantity: components["schemas"]["Quantity"];
                    /** @enum {string} */
                    side: "DEBIT" | "CREDIT";
                }[];
                reason_code?: string;
            };
            evidence_ref: string;
            reason: string;
        };
        SessionSummary: {
            created_at: components["schemas"]["Timestamp"];
            current?: boolean;
            device_label?: string;
            expires_at: components["schemas"]["Timestamp"];
            id: components["schemas"]["UUID"];
            ip?: string;
            last_seen_at: components["schemas"]["Timestamp"];
            revoked_at?: components["schemas"]["Timestamp"];
            user_agent?: string;
        };
        StartDepositRequest: {
            account_id: components["schemas"]["UUID"];
            fiat_amount: string;
            /** @enum {string} */
            fiat_currency: "USD";
            funding_source_id?: components["schemas"]["UUID"];
        };
        StatusChange: {
            policy_version?: string;
            reason: string;
            to: string;
        };
        StreamEvent: {
            data?: {
                [key: string]: unknown;
            };
            /** @description cursor; monotonically increasing per connection */
            id: string;
            occurred_at: components["schemas"]["Timestamp"];
            resource_id?: string;
            /** @enum {string} */
            type: "buying_power.changed" | "order.transitioned" | "intent.transitioned" | "deposit.transitioned" | "agent.state" | "resync";
        };
        SubmitIntentRequest: {
            account_id: components["schemas"]["UUID"];
            action: components["schemas"]["IntentAction"];
            constraints?: components["schemas"]["IntentConstraints"];
            deadline?: components["schemas"]["Timestamp"];
            instrument_id: components["schemas"]["UUID"];
            /**
             * @description Manual trades are PAPER until LIVE_MANUAL_TRADING is ACTIVE
             * @enum {string}
             */
            mode: "PAPER" | "LIVE";
            notional_usd?: components["schemas"]["USD"];
            quantity?: components["schemas"]["Quantity"];
            /** @description Preview quote the user saw; the planner re-quotes and validates freshness */
            quote_id?: components["schemas"]["UUID"];
            target_exposure_usd?: components["schemas"]["USD"];
        };
        /** Format: date-time */
        Timestamp: string;
        TradeIntent: {
            account_id: components["schemas"]["UUID"];
            action: components["schemas"]["IntentAction"];
            /** @enum {string} */
            actor_type: "USER" | "AGENT" | "OPERATOR";
            agent_id?: components["schemas"]["UUID"];
            constraints?: components["schemas"]["IntentConstraints"];
            correlation_id: string;
            deadline?: components["schemas"]["Timestamp"];
            id: components["schemas"]["UUID"];
            instrument_id: components["schemas"]["UUID"];
            /** @enum {string} */
            mode: "BACKTEST" | "PAPER" | "SHADOW" | "CANARY" | "LIMITED" | "LIVE";
            notional_usd?: components["schemas"]["USD"];
            order_id?: components["schemas"]["UUID"];
            plan_id?: components["schemas"]["UUID"];
            quantity?: components["schemas"]["Quantity"];
            received_at: components["schemas"]["Timestamp"];
            rejection_code?: string;
            requested_at: components["schemas"]["Timestamp"];
            /** @enum {string} */
            status: "RECEIVED" | "ELIGIBILITY_CHECKED" | "RISK_CHECKED" | "RESERVED" | "PLANNED" | "EXECUTING" | "COMPLETED" | "REJECTED" | "EXPIRED" | "CANCELLED" | "FAILED" | "NO_VALID_PLAN";
            target_exposure_usd?: components["schemas"]["USD"];
            terminal_at?: components["schemas"]["Timestamp"];
        };
        TradeIntentDetail: components["schemas"]["TradeIntent"] & {
            eligibility?: components["schemas"]["Decision"];
            order?: components["schemas"]["Order"];
            plan?: {
                [key: string]: unknown;
            };
            reservation?: {
                [key: string]: unknown;
            };
            risk?: components["schemas"]["Decision"];
            transitions?: {
                from: string;
                occurred_at: components["schemas"]["Timestamp"];
                reason?: string;
                to: string;
            }[];
        };
        TradeIntentPage: components["schemas"]["Page"] & {
            items: components["schemas"]["TradeIntent"][];
        };
        /**
         * @description USD as a decimal string with exactly two fraction digits
         * @example 1234.56
         */
        USD: string;
        /**
         * Format: uuid
         * @description UUIDv7 in canonical form
         */
        UUID: string;
        VenueListing: {
            base_mint?: string;
            base_precision: number;
            id: components["schemas"]["UUID"];
            max_notional_quote?: components["schemas"]["Quantity"];
            min_notional_quote: components["schemas"]["Quantity"];
            network: string;
            quote_mint?: string;
            quote_precision: number;
            /** @enum {string} */
            status: "ACTIVE" | "DEGRADED" | "DISABLED";
            venue: string;
            /** @enum {string} */
            venue_status: "ACTIVE" | "DEGRADED" | "DISABLED";
        };
        Withdrawal: {
            account_id: components["schemas"]["UUID"];
            asset_id: components["schemas"]["UUID"];
            created_at: components["schemas"]["Timestamp"];
            destination_address: string;
            id: components["schemas"]["UUID"];
            quantity: components["schemas"]["Quantity"];
            status: string;
        };
        WithdrawalRequest: {
            account_id: components["schemas"]["UUID"];
            asset_id: components["schemas"]["UUID"];
            destination_address: string;
            quantity: components["schemas"]["Quantity"];
        };
    };
    responses: {
        /** @description Structured error */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        AccountId: components["schemas"]["UUID"];
        Cursor: string;
        DepositId: components["schemas"]["UUID"];
        /** @description Same key + same body replays the original result; same key + different body → 409 INVALID_IDEMPOTENCY_REUSE. The key is opaque to the server but constrained to an unambiguous charset: it becomes part of a primary key, is echoed in responses, and is written to logs and audit records, so control characters and quoting metacharacters are refused at the edge rather than escaped correctly at every one of those sinks forever. Every legitimate key already satisfies this — newIdempotencyKey() returns a UUID. */
        IdempotencyKey: string;
        InstrumentId: components["schemas"]["UUID"];
        IntentId: components["schemas"]["UUID"];
        Limit: number;
        OrderId: components["schemas"]["UUID"];
        SessionId: components["schemas"]["UUID"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
