package config

import (
	"bufio"
	"fmt"
	"io"
	"strings"
)

// ExampleEnv renders the content of the repository's .env.example: every
// CP_* variable in documentation order with its LOCAL value. It is generated
// from the same table that drives Load, and the config tests keep the
// committed file in sync (run `go test ./internal/config -run TestExampleEnv
// -update` after changing the table).
func ExampleEnv() string {
	var b strings.Builder
	b.WriteString("# .env.example -- GENERATED by `go test ./internal/config -run TestExampleEnv -update`.\n")
	b.WriteString("# Do not edit by hand; edit the variable table in internal/config/load.go.\n")
	b.WriteString("#\n")
	b.WriteString("# LOCAL developer values only. Never put production secrets in this file, the\n")
	b.WriteString("# repository, a Docker image or the frontend (goal PART 99). Copy to .env\n")
	b.WriteString("# (git-ignored) and adjust.\n")
	b.WriteString("#\n")
	b.WriteString("# Defaults shown below are applied by Load ONLY when CP_ENV is LOCAL or TEST.\n")
	b.WriteString("# In DEV, STAGING and PROD every variable marked \"required\" must be set\n")
	b.WriteString("# explicitly; a missing value is a startup error, never a silent default.\n")
	b.WriteString("# STAGING/PROD additionally reject fake providers, dev/debug auth, seeding,\n")
	b.WriteString("# non-TLS data stores, CORS wildcards, plain-text secrets, and require the\n")
	b.WriteString("# archive, Object Lock, KMS signing key, secure cookies and https URLs.\n")

	section := ""
	for _, s := range specs() {
		if s.Section != section {
			section = s.Section
			fmt.Fprintf(&b, "\n# ==== %s ====\n", section)
		}
		b.WriteString("\n")
		for _, line := range wrap(s.Doc, 94) {
			b.WriteString("# " + line + "\n")
		}
		var notes []string
		switch {
		case s.Required && s.Default != "":
			notes = append(notes, "required outside LOCAL/TEST", "LOCAL/TEST default: "+s.Default)
		case s.Required:
			notes = append(notes, "required")
		default:
			notes = append(notes, "optional")
		}
		if s.Dep != "" {
			notes = append(notes, "only required of a service that uses "+s.Dep.String())
		}
		if s.Svc != "" {
			notes = append(notes, "only required of "+s.Svc.String())
		}
		if s.Secret {
			notes = append(notes, "SecretRef (env://NAME | aws-sm://name-or-arn | file://path | plain in LOCAL/TEST)")
		}
		b.WriteString("# [" + strings.Join(notes, "; ") + "]\n")
		value := s.Example
		if value == "" {
			value = s.Default
		}
		fmt.Fprintf(&b, "%s=%s\n", s.Name, quoteDotEnv(value))
	}
	return b.String()
}

func quoteDotEnv(v string) string {
	if strings.ContainsAny(v, " #\"'\t") {
		return `"` + strings.ReplaceAll(v, `"`, `\"`) + `"`
	}
	return v
}

func wrap(text string, width int) []string {
	var lines []string
	var cur strings.Builder
	for _, w := range strings.Fields(text) {
		if cur.Len() > 0 && cur.Len()+1+len(w) > width {
			lines = append(lines, cur.String())
			cur.Reset()
		}
		if cur.Len() > 0 {
			cur.WriteByte(' ')
		}
		cur.WriteString(w)
	}
	if cur.Len() > 0 {
		lines = append(lines, cur.String())
	}
	return lines
}

// ParseDotEnv reads KEY=VALUE lines (blank lines and # comments ignored, an
// optional "export " prefix allowed, surrounding double or single quotes
// stripped). It is the inverse of ExampleEnv and is intended for LOCAL/TEST
// tooling; deployed environments receive variables from the platform.
func ParseDotEnv(r io.Reader) (map[string]string, error) {
	out := map[string]string{}
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	lineNo := 0
	for sc.Scan() {
		lineNo++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line = strings.TrimPrefix(line, "export ")
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			return nil, fmt.Errorf("config: dotenv line %d: expected KEY=VALUE", lineNo)
		}
		k = strings.TrimSpace(k)
		if !envNameRe.MatchString(k) {
			return nil, fmt.Errorf("config: dotenv line %d: invalid variable name %q", lineNo, k)
		}
		v = strings.TrimSpace(v)
		if len(v) >= 2 {
			if q := v[0]; (q == '"' || q == '\'') && v[len(v)-1] == q {
				v = v[1 : len(v)-1]
				if q == '"' {
					v = strings.ReplaceAll(v, `\"`, `"`)
				}
			}
		}
		out[k] = v
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("config: dotenv: %w", err)
	}
	return out, nil
}

// LookupFromMap adapts a map to the lookup signature accepted by Load.
func LookupFromMap(m map[string]string) func(string) (string, bool) {
	return func(k string) (string, bool) {
		v, ok := m[k]
		return v, ok
	}
}
